export enum PERSONAL_STEP_ERROR_CODE {
  NAME_IS_TOO_SMALL = "NAME_IS_TOO_SMALL",
  NAME_IS_TOO_BIG = "NAME_IS_TOO_BIG",
  SURNAME_IS_TOO_SMALL = "SURNAME_IS_TOO_SMALL",
  SURNAME_IS_TOO_BIG = "SURNAME_IS_TOO_BIG",
  PATRONYMIC_IS_TOO_SMALL = "PATRONYMIC_IS_TOO_SMALL",
  PATRONYMIC_IS_TOO_BIG = "PATRONYMIC_IS_TOO_BIG",
  EMAIL_IS_INVALID = "EMAIL_IS_INVALID",
  PHONE_NUMBER_IS_INVALID = "PHONE_NUMBER_IS_INVALID",
  POSITION_IS_TOO_SMALL = "POSITION_IS_TOO_SMALL",
  POSITION_IS_TOO_BIG = "POSITION_IS_TOO_BIG",
  TERMS_ARE_NOT_ACCEPTED = "TERMS_ARE_NOT_ACCEPTED",
  PRIVACY_POLICY_NOT_ACCEPTED = "PRIVACY_POLICY_NOT_ACCEPTED",
}
