export enum ORGANIZATION_STEP_ERROR_CODE {
  ORGANIZATION_NAME_IS_TOO_SMALL = "ORGANIZATION_NAME_IS_TOO_SMALL",
  ORGANIZATION_NAME_IS_TOO_BIG = "ORGANIZATION_NAME_IS_TOO_BIG",
  WEBSITE_IS_INVALID = "WEBSITE_IS_INVALID",
  ADDRESS_IS_TOO_SMALL = "ADDRESS_IS_TOO_SMALL",
  ADDRESS_IS_TOO_BIG = "ADDRESS_IS_TOO_BIG",
  COUNTRY_IS_REQUIRED = "COUNTRY_IS_REQUIRED",
  CITY_IS_TOO_SMALL = "CITY_IS_TOO_SMALL",
  CITY_IS_TOO_BIG = "CITY_IS_TOO_BIG",
  POSTAL_CODE_IS_TOO_SMALL = "POSTAL_CODE_IS_TOO_SMALL",
  POSTAL_CODE_IS_TOO_BIG = "POSTAL_CODE_IS_TOO_BIG",
}
