export enum VERIFICATION_ERROR_CODE {
  OTP_IS_REQUIRED = "OTP_IS_REQUIRED",
  OTP_IS_INVALID = "OTP_IS_INVALID",
  DRAFT_IS_REQUIRED = "DRAFT_IS_REQUIRED",
  INVALID_EMAIL_CODE = "INVALID_EMAIL_CODE",
  SEND_EMAIL_FAILED = "SEND_EMAIL_FAILED",
  VERIFY_EMAIL_FAILED = "VERIFY_EMAIL_FAILED",
  COMPLETE_REGISTRATION_FAILED = "COMPLETE_REGISTRATION_FAILED",
}
